services:
  api:
    container_name: "snippet-engine-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: snippet-engine-db
      DB_HOST: postgres_db_engine
      DB_PORT: 5432

  db:
    container_name: postgres_db_engine
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippet-engine-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: