permissions:
  contents: write
  packages: write
name: SnippetEngine CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
  push_to_registry:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create Short SHA
          uses: benjlevesque/short-sha@v1.2
          id: short-sha
          with:
            length: 8

        - name: Set up Docker Buildx (multi-platform / builder)
          uses: docker/setup-buildx-action@v2

        - name: Login to GHCR
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.short-sha.outputs.sha }}
              ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
  deploy:
    needs: push_to_registry
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_PUBLIC_IP }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.RSA_VM_KEY }}
          script: |
            cd ~/infra
            ./start-docker.sh